import 'package:flutter/material.dart';

class RazonesScreen extends StatelessWidget {
  const RazonesScreen({super.key});

  // 100 razones por las que la amas
  final List<String> razones = const [
    "Porque iluminas mi vida con tu sonrisa.",
    "Porque haces que cada día sea especial.",
    "Porque me haces sentir amado.",
    "Porque tus abrazos son mi refugio.",
    "Porque tus ojos reflejan ternura.",
    "Porque me haces reír incluso en los peores días.",
    "Porque tu voz es música para mi corazón.",
    "Porque me apoyas siempre en todo.",
    "Porque eres mi inspiración diaria.",
    "Porque compartes tus sueños conmigo.",
    "Porque eres mi compañera de aventuras.",
    "Porque tus palabras me llenan de calma.",
    "Porque tu amor me hace mejor persona.",
    "Porque siempre sabes cómo animarme.",
    "Porque haces que todo valga la pena.",
    "Porque tu corazón es inmenso y generoso.",
    "Porque tu risa es contagiosa.",
    "Porque me entiendes sin que diga nada.",
    "Porque me haces sentir completo.",
    "Porque juntos todo es más divertido.",
    "Porque me haces creer en el amor verdadero.",
    "Porque me enseñas a ser paciente y fuerte.",
    "Porque tu mirada me derrite.",
    "Porque eres mi hogar sin importar el lugar.",
    "Porque tu cariño es mi tesoro.",
    "Porque me das paz y alegría.",
    "Porque siempre estás a mi lado.",
    "Porque tu sinceridad me inspira confianza.",
    "Porque eres única e irrepetible.",
    "Porque tus abrazos curan cualquier tristeza.",
    "Porque haces que cada momento sea mágico.",
    "Porque me haces sentir especial.",
    "Porque tu belleza va más allá de lo físico.",
    "Porque compartimos risas y secretos.",
    "Porque tus detalles muestran tu amor.",
    "Porque siempre encuentras la manera de sorprenderme.",
    "Porque eres mi mejor amiga y amante.",
    "Porque tus sueños se vuelven también mis sueños.",
    "Porque me haces sentir seguro.",
    "Porque tu ternura no tiene límites.",
    "Porque eres mi paz en medio del caos.",
    "Porque juntos superamos todo.",
    "Porque tu cariño me envuelve y protege.",
    "Porque tu risa alegra mi alma.",
    "Porque me inspiras a ser creativo y feliz.",
    "Porque contigo la vida es más dulce.",
    "Porque compartimos momentos inolvidables.",
    "Porque me haces sentir importante.",
    "Porque tu honestidad me enseña a ser mejor.",
    "Porque eres mi razón de sonreír.",
    "Porque cada día contigo es un regalo.",
    "Porque tus palabras me llenan de esperanza.",
    "Porque juntos creamos recuerdos eternos.",
    "Porque me das fuerza cuando estoy débil.",
    "Porque tu amor es incondicional.",
    "Porque me haces sentir vivo.",
    "Porque siempre piensas en mí.",
    "Porque tus abrazos son mi lugar favorito.",
    "Porque contigo aprendo a amar de verdad.",
    "Porque me haces ver la belleza de todo.",
    "Porque tu energía es contagiosa.",
    "Porque siempre me apoyas en mis locuras.",
    "Porque tu mirada dice más que mil palabras.",
    "Porque eres mi confidente.",
    "Porque contigo todo es más fácil.",
    "Porque tu amor es mi motor.",
    "Porque me haces sentir único.",
    "Porque juntos somos invencibles.",
    "Porque tu ternura me conmueve.",
    "Porque eres mi sol en los días nublados.",
    "Porque me haces sentir orgulloso de amarte.",
    "Porque tu risa ilumina mi mundo.",
    "Porque compartimos secretos y sueños.",
    "Porque tu compañía es mi felicidad.",
    "Porque tus abrazos me dan seguridad.",
    "Porque eres mi alegría diaria.",
    "Porque cada palabra tuya es un regalo.",
    "Porque me haces reír sin esfuerzo.",
    "Porque tu amor me completa.",
    "Porque tu mirada me enamora cada día.",
    "Porque eres mi inspiración para todo.",
    "Porque me haces querer ser mejor.",
    "Porque contigo todo es más bonito.",
    "Porque tu cariño es sincero y profundo.",
    "Porque tu sonrisa me derrite.",
    "Porque tu amor me da alas.",
    "Porque eres mi mejor compañía.",
    "Porque me enseñas a disfrutar la vida.",
    "Porque tus detalles me emocionan.",
    "Porque me haces sentir especial cada día.",
    "Porque juntos hacemos recuerdos inolvidables.",
    "Porque tu amor me transforma.",
    "Porque tu ternura me calma.",
    "Porque eres mi lugar seguro.",
    "Porque me haces ver lo maravilloso de la vida.",
    "Porque tu risa es mi melodía favorita.",
    "Porque me haces sentir amado sin condiciones.",
    "Porque eres mi todo.",
    "Porque juntos soñamos en grande.",
    "Porque tu amor no tiene límites.",
    "Porque me llenas de felicidad.",
    "Porque eres mi paz y mi alegría.",
    "Porque contigo aprendo a amar más.",
    "Porque tu cariño es mi refugio.",
    "Porque cada día contigo es un regalo.",
    "Porque te amo con todo mi corazón.",
    "Porque eres perfecta para mí.",
    "Porque tu amor es mi razón de vivir.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Razones por las que te amo",
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
        ),
        backgroundColor: const Color.fromARGB(255, 148, 7, 7),
        centerTitle: true,
        elevation: 0,
      ),
      body: Container(
        color: Colors.pink[50],
        child: ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: razones.length,
          itemBuilder: (context, index) {
            return Card(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              color: Colors.white.withOpacity(0.9),
              elevation: 6,
              margin: const EdgeInsets.symmetric(vertical: 8),
              child: ListTile(
                contentPadding: const EdgeInsets.all(16),
                leading: const Icon(
                  Icons.favorite,
                  color: Colors.red,
                  size: 36,
                ),
                title: Text(
                  "Razón ${index + 1}",
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.redAccent,
                  ),
                ),
                subtitle: Padding(
                  padding: const EdgeInsets.only(top: 8.0),
                  child: Text(
                    razones[index],
                    style: const TextStyle(fontSize: 16, height: 1.4),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
